In [2]:
import numpy as np
x = np.array([0,1])  # Giá trị X có thể nhận
y = np.array([0,1,2])   # Giá trị Y có thể nhận
jpmf = np.array([[0.38,0.17], [0.14,0.02], [0.24,0.05]])  #Ma trận trọng số

print(jpmf)

[[0.38 0.17]
 [0.14 0.02]
 [0.24 0.05]]


In [4]:
pmfx = [] # hàm trọng số biên của X

for i in x:
    pmfx.append(jpmf[:,i].sum())

print(pmfx)    

[0.76, 0.24]


In [5]:
pmfy = [] # hàm trọng số biên của Y

for i in y:
    pmfy.append(jpmf[i,:].sum())

print(pmfy)    

[0.55, 0.16, 0.29]


In [6]:
EX = np.sum(x*pmfx); EY = np.sum(y*pmfy) # kỳ vọng của từng biến

varX = np.sum((x-EX)**2*pmfx); varY = np.sum((y-EY)**2*pmfy) # phương sai


In [7]:
EXY = 0

for i in x: 
    for j in y:
        EXY = EXY + i*j*jpmf[j,i]


print(EXY)        

0.12000000000000001


In [8]:
cov = EXY - EX*EY

In [9]:
import seaborn as sns

mean = [165,55]
cov = [[81,0.6], [0.6,36]]

chieu_cao, can_nang = np.random.multivariate_normal(mean, cov, 1000).T
sns.jointplot(chieu_cao, can_nang, stat_func=None).set_axis_labels("chiều cao", "cân nặng")

TypeError: jointplot() takes from 0 to 1 positional arguments but 2 were given

In [12]:
x = np.array([0,1,2])  # Giá trị X có thể nhận
y = np.array([0,1,2])   # Giá trị Y có thể nhận

joint_pmf = np.array([[0.1, 0.2, 0.1], [0.15, 0.05, 0.2], [0.05, 0.1, 0.05]])

print(joint_pmf)

[[0.1  0.2  0.1 ]
 [0.15 0.05 0.2 ]
 [0.05 0.1  0.05]]


In [17]:
joint_pmf = {
    (0,0): 0.1,
    (0,1): 0.2,
    (0,2): 0.1,
    (1,0): 0.15,
    (1,1): 0.05,
    (1,2): 0.2,
    (2,0): 0.05,
    (2,1): 0.1,
    (2,2): 0.05,

}



In [18]:
print("Join pmf P(X=x, Y=y):")
for (x,y), prob in joint_pmf.items():
    print(f"P(X={x}, Y={y}) = {prob:.2f}")
total_prob = sum(joint_pmf.values())    

Join pmf P(X=x, Y=y):
P(X=0, Y=0) = 0.10
P(X=0, Y=1) = 0.20
P(X=0, Y=2) = 0.10
P(X=1, Y=0) = 0.15
P(X=1, Y=1) = 0.05
P(X=1, Y=2) = 0.20
P(X=2, Y=0) = 0.05
P(X=2, Y=1) = 0.10
P(X=2, Y=2) = 0.05


In [19]:
marginal_pmf_X = {}
marginal_pmf_Y = {}

for (x,y), prob in joint_pmf.items():
    if x not in marginal_pmf_X:
        marginal_pmf_X[x]=0
    marginal_pmf_X[x]+=prob

# Compute the marginal PMF for Y
for (x,y), prob in joint_pmf.items():
    if y not in marginal_pmf_Y:
        marginal_pmf_Y[y]=0
    marginal_pmf_Y[y]+=prob


print("Marginal PMF P(X=x):")
for x, prob in marginal_pmf_X.items():
    print(f"P(X={x})={prob:.2f}")


print("Marginal PMF P(Y=y):")
for y, prob in marginal_pmf_Y.items():
    print(f"P(X={y})={prob:.2f}")
    



Marginal PMF P(X=x):
P(X=0)=0.40
P(X=1)=0.40
P(X=2)=0.20
Marginal PMF P(Y=y):
P(X=0)=0.30
P(X=1)=0.35
P(X=2)=0.35


In [22]:
probability = 0


for (x,y), prob in joint_pmf.items():
    if x>1 and y>0:
        probability += prob
print("Probability when X>1 and Y>0:", f"{probability:.2f}")        
        

Probability when X>1 and Y>0: 0.15


In [23]:
probability = 0
for (x,y), prob in joint_pmf.items():
    if x<=1 and y>=1:
        probability += prob
print("Probability when X<=1 and Y>=1:", f"{probability:.2f}")    

Probability when X<=1 and Y>=1: 0.55


In [25]:

p_XY = 0
P_Y = 0
for (x,y), prob in joint_pmf.items():
    if x<=1 and y>=1:
        p_XY += prob
    if y>=1:
        P_Y += prob    
print("Probability when X<=1 in case Y>=1:", f"{p_XY/P_Y:.2f}")   





Probability when X<=1 in case Y>=1: 0.79


## Homework

Bài tập 4.1:
cho bảng phân phối xác suất như dưới đây. 
1. Tìm hàm phân phối biên của X, Y
2. Tìm kỳ vọng, phương sai của X,Y
3. Tìm $cov(X,Y)$, hệ số tương quan
4. Tìm ma trận hiệp phương sai của $(X,Y)$

In [5]:


joint_pmf = {
    (0,0): 0.08,
    (0,1): 0.09,
    (0,2): 0.05,
    (1,0): 0.14,
    (1,1): 0.17,
    (1,2): 0.18,
    (2,0): 0.12,
    (2,1): 0.13,
    (2,2): 0.04
}

print(sum(joint_pmf.values()))

1.0


In [11]:
marginal_pmf_X = {}
marginal_pmf_Y = {}
for (x,y), prob in joint_pmf.items():
        if x not in marginal_pmf_X:
                marginal_pmf_X[x] = 0
        marginal_pmf_X[x]+=prob 

        if y not in marginal_pmf_Y:
                marginal_pmf_Y[y] = 0
        marginal_pmf_Y[y]+=prob       


print(sum(marginal_pmf_X.values()))



1.0


In [18]:
import numpy as np

In [22]:
EX = 0
for key, value in marginal_pmf_X.items():
    EX  += key*value

EX    

1.07

In [23]:
EY = 0
for key, value in marginal_pmf_Y.items():
    EY  += key*value

EY

0.9299999999999999

$cov(X,Y)= E(XY)-EX*EY$

In [24]:
EXY = 0
for (x,y), prob in joint_pmf.items():
    EXY += x*y*prob

EXY    

0.9500000000000001

In [26]:
covXY = EXY - EX*EY

covXY

-0.04509999999999992

#### Covariance matrix 

In [31]:
EX2 = 0
EY2 = 0
for key, value in marginal_pmf_X.items():
    EX2  += key*value**2
for key, value in marginal_pmf_Y.items():
    EY2  += key*value**2    

print(EX2, EY2, sep='\n')   

0.4083
0.29789999999999994


In [32]:
varX = EX - EX2
varY = EY - EY2


In [36]:
covXY = np.array([[varX, EXY], [EXY, varY]])
covXY

array([[0.6617, 0.95  ],
       [0.95  , 0.6321]])

#### Bài tập 4.2:
Cho hai biến ngẫu nhiên tuân theo luật phân phối chuẩn độc lập với nhau có kỳ vọng lần lượt là 30, 40 và độ lệch chuẩn là 2 và 3
1. Tìm ma trận hiệp phương sai
2. Biểu diễn vecto kỳ vọng, ma trận hiệp phương sai qua python
3. Dùng lệnh np.random.multivariate_normal để tạo ra 500 giá trị
4. Vẽ đồ thị các giá trị đồng mà $(X,Y)$ có thể nhận và phân phối biên trong cùng một đồ thị.

$F(x)= x*e^{-x}$ with $x>=0$ and
$F(x)= 0$ with $x<0$

In [47]:
from scipy.integrate import quad
import numpy as np
# count the expected
def ham_f(x):
    return x**2*np.exp(-x)

I = quad(ham_f, 0, np.inf)[0]
I

2.0

In [51]:
# tuoi tho bong den lon hon 3
def prob(x):
    return x*np.exp(-x)
p = quad(prob, 3, np.Inf)[0]
print(p)

0.19914827347145575


In [58]:

a = np.random.randint(0,1000)
b = np.random.randint(0,1000)

def ham_pdf_x(y):
    return 1/a*1/b

print(a,b,sep='\n')
I = quad(ham_pdf_x, 0, b)[0]

print(I)
print(1/a)


59
247
0.01694915254237288
0.01694915254237288
